### PR TITLE
Rename dir 'test' to 'test-env'.

### LINKED ISSUE #144: Conflict with yarn autoclean
The [`yarn autoclean`](https://classic.yarnpkg.com/en/docs/cli/autoclean/) default `.yarnclean` values includes `test`, which conflicts with part of this package.

Specifically, there's a directory called `test` located within the package: https://github.com/gsoft-inc/craco/tree/master/packages/craco/lib/features/test

I suggest renaming that path so it doesn't get wiped out by autoclean.

### PR DESCRIPTION
**Pull request by brndnmtthws**
This resolves #144 by fixing a conflict with the `yarn autoclean`
defaults.

### CODE REVIEW

**Comment by patricklafrance** [comment]
Thanks for the PR.

Sorry I was away on vacation, I will have a look at it next week.

Patrick

**Comment by patricklafrance** [comment]
@brndnmtthws thanks for taking care of this, definitely have of to be fix.

I am not sure about the name "test-env" though, could you rename the folder to "jest" instead please?

Thanks,

Patrick

**Comment by polarathene** [comment]
That bot is a bit aggressive? Only one month of inactivity? I haven't run into the issue personally but if this hasn't been resolved since, you probably want the PR re-opened and a notstale label to keep the bot away.

**Comment by Grawl** [comment]
I think we don't want to remove all tests from our `node_modules`. Some package may want to test itself on install lifecycle for example, or `test/` folder may be named to store regular expressions or something like this.

**Comment by patricklafrance** [comment]
Fixed in https://github.com/gsoft-inc/craco/commit/c6a00232bb65730254bd8afff43bd5deb89d745b

**Pull request closed without merging**
