### PR TITLE
fixes peer dependency issue and updates README

### PR DESCRIPTION
**Pull request by ImanMh**
Supporting Craco for CRA-5. This will fix the issue of "peer react-scripts@"^4.0.0" from @craco/craco@6.4.3".

### CODE REVIEW

**Comment by patricklafrance** [comment]
Hi @ImanMh 

Thanks for the PR.

Unfortunately, before upgrading the dependency to react-script 5 the issues between CRA 5 and CRACO must be resolved.

If you want to to contribute, have a look at these: https://github.com/gsoft-inc/craco/issues/353 https://github.com/gsoft-inc/craco/issues/313

Thank you

**Comment by ImanMh** [comment]
Hi @patricklafrance ,

I thought the order does not matter since it's on branch "support-cra5". You've merged [!332](https://github.com/gsoft-inc/craco/pull/332) and I saw that everything seems to be working except that you can't install CRACO when you have CRA@5 installed. Can you also mention what things are not working at this moment?

**Comment by patricklafrance** [comment]
Oh sorry I haven’t notice your PR is for the support branch.

**Comment by ImanMh** [comment]
No problems bro, I guessed you might not see that. Anyways It seems like everything is working now. That would be great if you can also publish an alpha version so we use it in real projects and fixing the issues as we encounter them.

**Pull request merged**
