### PR TITLE
Updates support for CRA 5.

### PR DESCRIPTION
**Pull request by plpaquin**

### CODE REVIEW

**Comment by plpaquin** [comment]
@patricklafrance Was this ready to go?

**Comment by Codex-** [comment]
Tested these changes out with our react-scripts v5 migration and am hitting mismatched snapshots 🤔 
```
  babel: {
    presets: [['@emotion/babel-preset-css-prop', { labelFormat: '[dirname]-[filename]-[local]' }]]
  },
```
Which may be correct now but not before? It's a little spooky lol:
image

**Comment by kitsunekyo** [comment]
i've created a PR on your fork to add the missing handling for the webpack5 `postcss-loader`

**Comment by arbaaz** [comment]
Any updates on this?

**Comment by plpaquin** [comment]
In the meantime, if anyone wants to test drive the changes from this pull request, they may do so using this temporary version here: [@plpaquin/craco](https://www.npmjs.com/package/@plpaquin/craco).

**Comment by ShvedDmytro** [comment]
will we have support CRA 5 ever ?

**Comment by Codex-** [comment]
> will we have support CRA 5 ever ?

Patience is a virtue: https://github.com/gsoft-inc/craco/issues/378

**Comment by SakirSoft** [comment]
BTW is there something we can do to help out this PR going through ?
Let me know if I can help somehow.

**Comment by Codex-** [comment]
> BTW is there something we can do to help out this PR going through ? Let me know if I can help somehow.

The issue for tracking this is: https://github.com/gsoft-inc/craco/issues/378

@olivierbeaulieu has kindly published `7.0.0-alpha.0` (huge thanks) 

Looks like progress is being made and any issues with the alpha should go there? 🙏

**Pull request closed without merging**
